databases:
  - name: price-db
    plan: free

services:
  - type: web
    name: price-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: price-db
          property: connectionString

  - type: cron
    name: price-scraper
    runtime: python
    schedule: "0 6 * * 1"          # Mo 06:00 UTC = 08:00 Wien
    buildCommand: pip install -r requirements.txt
    startCommand: python app/scraper.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: price-db
          property: connectionString
